### PR TITLE
linting for juttle-viz

### PR DESCRIPTION
**Pull request by rlgomes**

### CODE REVIEW

**Comment by rlgomes** [comment]
@go-oleg @mnibecker linting!

**Comment by mattnibs** [comment]
why are we using jshint and jscrc over us eslint? Does jshint + jscrc allow for es6 + babel linting?

**Comment by rlgomes** [comment]
I shall look into using eslint as I was just keeping with the jshint + jscs combo used in other juttle projects.

**Comment by mattnibs** [comment]
@rlgomes I used it with great success in juttle/juttle-client-library

**Comment by rlgomes** [comment]
@go-oleg @mnibecker noicer ?

**Comment by rlgomes** [comment]
@mnibecker I didn't include the double quote vs single quote enforcement since this we have yet to reach an agreement on that.

@demmer @dmajda @mstemm @go-oleg @VladVega @davidvgalbraith @dmehra cast your votes on single quotes everywhere vs double quotes in our codebase  as we're primarly single quotes in juttle but we've enforced the double quote requirement in https://github.com/juttle/juttle-client-library and I really feel it would be easier if we picked one and stuck to it.

**Comment by mattnibs** [comment]
+1
Nooice

**Comment by mattnibs** [comment]
I don't care double or single, but i think it should be a rule.

**Comment by demmer** [comment]
Re double vs single quotes, when this has come up in the past I've always felt it's not worth enforcing a consistent style.

**Comment by mstemm** [comment]
I vote for not specifically enforcing either single or double quotes.

**Comment by dmajda** [comment]
I’d like us to standardize on one kind of quotes. Different kinds of quotes create an unnecessary inconsistency, and most projects with some conventions do standardize this. Technically it doesn’t matter which quotes we choose, pragmatically it makes more sense to stick with single ones (because we use them most in the codebase).

**Comment by mattnibs** [comment]
In agreement with dmajda here- in the old product repo I found it kind of annoying how we would switch from double to single on a pre file basis. Some uniformity here would be much appreciated.

**Pull request merged**
