### PR TITLE
Add npm prepublish support

### PR DESCRIPTION
**Pull request by mattnibs**
With our current setup we were running into a couple issues when
importing juttle-viz into other libraries. 1) We couldn't import
and browserify the library because we weren't babelify the source
and 2) We weren't generating a javascript blob that I can throw
into my browser.

What I did here:
- Created `gulp lib` task that run all js code through babel and spits
  it out into a lib dir. As such I've pointed the entry to lib/index.js.
  Now requiring juttle-viz should "Just Work"(TM).
- From the above had to rename folder lib in src to ext so my .gitignore
  on lib wouldn't remove lib from src/lib. I don't think src should have a
  folder called lib anyways.
- Add a `gulp clean` command that removes generated dirs (lib, build and
  test/build)
- Add an npm "prepublish" script that cleans the repo then generates the
  babelified lib and browserify artifact.

Moving forward: Kind of weird that babel has two different libraries:
gulp-babel and gulp-babelify. Ideally we create the artifact and lib
using the same babel lib. In a future pr we might want to use webpack
while might give us the flexibility that we need.

### CODE REVIEW

**Comment by mattnibs** [comment]
@rlgomes @demmer (if @go-oleg is still around)

**Comment by go-oleg** [comment]
@mnibecker, thanks...definitely need to have build artifacts that can be included in the browser or required.

Some thoughts/questions:
- I haven't seen the `ext` convention anywhere...can you point me to a js lib that uses that? If you are trying to prevent `.gitignore` from ignoring a nested `lib` folder, you can add `/lib` in the `.gitignore` instead of `lib`. As far as having a `lib` folder under `src`, I'm not sure why thats bad. We could move the folders in there to be directly in `src` or organize them in some other way.
- As far as depending on both `babelify` and `gulp-babel` goes, I think if you have `browserify` work on the output of your `lib` task, then it no longer needs `babelify`, so you could get rid of that dependency there.
- <del>Why is the `index.js` in `lib` and not in `src`?</del> sry, misread, it is in `src`
- Browserify lets you specify transforms directly inside `package.json` in a [`browserify` property](https://github.com/substack/node-browserify#browserifytransform) which tells browserify what transforms need to be applied. This is super convenient for consumers of this lib that use browserify to build their applications because they can browserify the whole thing without having to worry about what transforms need to be applied to this specific library. Perhaps adding this to the `package.json` would be a good idea. I tried to find something similar for webpack but couldn't...do you know if it exists?

**Comment by mattnibs** [comment]
Thanks for your feedback @go-oleg.
- @rlgomes and I kind of discussed this. I decided to do this because 1) the whole `.gitignore` thing and 2) with the lib output you would have a folder called `lib/lib` which I thought was kind of weird. Honestly I think the best solution would be to just flatten the whole thing. I think for right now I'll just keep it `lib` and we can discuss this at a later date.
- Yeah but then in dev mode you'll have to wait for `gulp-babel` to rewrite the entire contents of lib, then for `browserify` to kick off and write its output. Seemed like a lot. I would prefer to ditch gulp altogether and go with webpack which would do this all in memory and be a lot faster and less weird.
- coo
- `webpack --config webpack.config.js`?

**Comment by mattnibs** [comment]
@go-oleg I got rid of the whole `ext` business.

**Comment by go-oleg** [comment]
snds good!

**Pull request merged**
