### PR TITLE
tests against node v5

### PR DESCRIPTION
**Pull request by rlgomes**

### CODE REVIEW

**Comment by rlgomes** [comment]
@go-oleg @mnibecker we were missing the testing against v5

**Comment by mattnibs** [comment]
Being that this library only runs in the browser in production I somewhat question the utility of running tests in Node 5 for this

**Comment by rlgomes** [comment]
If we ran in atom as a plugin would it still be within the context of a browser ? (ie webkit engine ?) If it really doesn't make sense then I'll close this.

**Comment by mattnibs** [comment]
That's a good reason. I don't think it hurts, and it also is good to make sure our build processes work in 4+5. +1

**Pull request merged**
